name: build-and-test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup dotnet
        uses: actions/setup-dotnet@v4
        with:
          global-json-file: global.json

      - name: Restore dependencies
        run: dotnet restore SerilogSinksInMemory.slnx

      - name: Build
        run: dotnet build -c Release --no-restore SerilogSinksInMemory.slnx

      - name: Unit tests
        run: dotnet test --solution SerilogSinksInMemory.slnx -c Release --no-build

      - name: Create local packages
        run: dotnet pack -c Release -o packages --no-build SerilogSinksInMemory.slnx

      - name: Get the version
        id: get_version
        uses: mavrosxristoforos/get-xml-info@1.0
        with:
          xml-file: './version.props'
          xpath: '//Version'

      - name: Run integration tests for FluentAssertions 5
        working-directory: test/Serilog.Sinks.InMemory.Assertions.Tests.Integration.FluentAssertions5
        run: |
          dotnet restore -p:Version=${{ steps.get_version.outputs.info }} --configfile ../../NuGet.integration.config
          dotnet test --no-restore -c Release --project Serilog.Sinks.InMemory.Assertions.Tests.Integration.FluentAssertions5.csproj

      - name: Run integration tests for FluentAssertions 6
        working-directory: test/Serilog.Sinks.InMemory.Assertions.Tests.Integration.FluentAssertions6
        run: |
          dotnet restore -p:Version=${{ steps.get_version.outputs.info }} --configfile ../../NuGet.integration.config
          dotnet test --no-restore -c Release --project Serilog.Sinks.InMemory.Assertions.Tests.Integration.FluentAssertions6.csproj

      - name: Run integration tests for FluentAssertions 7
        working-directory: test/Serilog.Sinks.InMemory.Assertions.Tests.Integration.FluentAssertions7
        run: |
          dotnet restore -p:Version=${{ steps.get_version.outputs.info }} --configfile ../../NuGet.integration.config
          dotnet test --no-restore -c Release --project Serilog.Sinks.InMemory.Assertions.Tests.Integration.FluentAssertions7.csproj

      - name: Run integration tests for FluentAssertions 8
        working-directory: test/Serilog.Sinks.InMemory.Assertions.Tests.Integration.FluentAssertions8
        run: |
          dotnet restore -p:Version=${{ steps.get_version.outputs.info }} --configfile ../../NuGet.integration.config
          dotnet test --no-restore -c Release --project Serilog.Sinks.InMemory.Assertions.Tests.Integration.FluentAssertions8.csproj

      - name: Run integration tests for AwesomeAssertions 8
        working-directory: test/Serilog.Sinks.InMemory.Assertions.Tests.Integration.AwesomeAssertions8
        run: |
          dotnet restore -p:Version=${{ steps.get_version.outputs.info }} --configfile ../../NuGet.integration.config
          dotnet test --no-restore -c Release --project Serilog.Sinks.InMemory.Assertions.Tests.Integration.AwesomeAssertions8.csproj

      - name: Run integration tests for AwesomeAssertions 9
        working-directory: test/Serilog.Sinks.InMemory.Assertions.Tests.Integration.AwesomeAssertions9
        run: |
          dotnet restore -p:Version=${{ steps.get_version.outputs.info }} --configfile ../../NuGet.integration.config
          dotnet test --no-restore -c Release --project Serilog.Sinks.InMemory.Assertions.Tests.Integration.AwesomeAssertions9.csproj

      - name: Run integration tests for Shouldly 4.x
        working-directory: test/Serilog.Sinks.InMemory.Assertions.Tests.Integration.Shouldly4
        run: |
          dotnet restore -p:Version=${{ steps.get_version.outputs.info }} --configfile ../../NuGet.integration.config
          dotnet test --no-restore -c Release --project Serilog.Sinks.InMemory.Assertions.Tests.Integration.Shouldly4.csproj
